### ISSUE TITLE
To-do list for website

### ISSUE THREAD

**Issue by Ethan040** [MaverickWire/MaverickWireWebsite#8]
# **Gallery:**
- [ ] Find new pictures, put them in img folder
- [ ] Code in new pictures

# **General Improvements:**
- [ ] Refine appearance, logo, and color palette
- [ ]  Improve compatibility with Mozilla Firefox
- [ ] Put logo above menu instead of on menu
- [ ] Use JS to add auto-updating copyright date
- [x] Experiment with fonts
- [ ] Use gradients for background
- [ ] Improve mobile compatibility (make mobile version, and let Cloudflare automatically redirect)
- [x] Refine code, remove unnecessary elements 
- [x] Use `* {` instead of `html {`

**Comment by Ethan040** [comment]
![image](https://user-images.githubusercontent.com/20361523/30782685-77ec1a78-a0fc-11e7-9445-69bca16354b5.png)
Current mobile compatibility

**Comment by Ethan040** [comment]
I'm considering either dropping mobile compatibility or making a separate mobile version.

**Comment by Ethan040** [comment]
List no longer relevant, closing issue
